version: "3"
services:
  golang:
    build: ./
    ports:
      - "80:8888"
#    links:
#      - "mysql"
#      - "redis"
    volumes:
      - .:/go
    tty: true
#  mysql:
#    image: mysql:5.7
#    ports:
#      - "3306:33066"
#    volumes:
#      - $HOME/docker/mysql:/var/lib/mysql/
#    environment:
#      MYSQL_ROOT_PASSWORD: 123456
#  redis:
#    image: redis
#    ports:
#      - "6379:63791"

